# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import automaticlights_pb2 as automaticlights__pb2


class AutomaticLightsStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TurnOnOff = channel.unary_unary(
                '/autoLights.AutomaticLights/TurnOnOff',
                request_serializer=automaticlights__pb2.Light.SerializeToString,
                response_deserializer=automaticlights__pb2.Light.FromString,
                )
        self.vote = channel.unary_unary(
                '/autoLights.AutomaticLights/vote',
                request_serializer=automaticlights__pb2.voto.SerializeToString,
                response_deserializer=automaticlights__pb2.voto.FromString,
                )
        self.status = channel.unary_unary(
                '/autoLights.AutomaticLights/status',
                request_serializer=automaticlights__pb2.Light.SerializeToString,
                response_deserializer=automaticlights__pb2.Light.FromString,
                )


class AutomaticLightsServicer(object):
    """The greeting service definition.
    """

    def TurnOnOff(self, request, context):
        """probes a node to see if its online
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def vote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AutomaticLightsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TurnOnOff': grpc.unary_unary_rpc_method_handler(
                    servicer.TurnOnOff,
                    request_deserializer=automaticlights__pb2.Light.FromString,
                    response_serializer=automaticlights__pb2.Light.SerializeToString,
            ),
            'vote': grpc.unary_unary_rpc_method_handler(
                    servicer.vote,
                    request_deserializer=automaticlights__pb2.voto.FromString,
                    response_serializer=automaticlights__pb2.voto.SerializeToString,
            ),
            'status': grpc.unary_unary_rpc_method_handler(
                    servicer.status,
                    request_deserializer=automaticlights__pb2.Light.FromString,
                    response_serializer=automaticlights__pb2.Light.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'autoLights.AutomaticLights', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AutomaticLights(object):
    """The greeting service definition.
    """

    @staticmethod
    def TurnOnOff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/autoLights.AutomaticLights/TurnOnOff',
            automaticlights__pb2.Light.SerializeToString,
            automaticlights__pb2.Light.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def vote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/autoLights.AutomaticLights/vote',
            automaticlights__pb2.voto.SerializeToString,
            automaticlights__pb2.voto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/autoLights.AutomaticLights/status',
            automaticlights__pb2.Light.SerializeToString,
            automaticlights__pb2.Light.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
