# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: automaticlights.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61utomaticlights.proto\x12\nautoLights\"\x15\n\x04voto\x12\r\n\x05OnOff\x18\x01 \x01(\x08\")\n\x05Light\x12\r\n\x05OnOff\x18\x01 \x01(\x08\x12\x11\n\tintensity\x18\x02 \x01(\x05\x32\xa6\x01\n\x0f\x41utomaticLights\x12\x33\n\tTurnOnOff\x12\x11.autoLights.Light\x1a\x11.autoLights.Light\"\x00\x12,\n\x04vote\x12\x10.autoLights.voto\x1a\x10.autoLights.voto\"\x00\x12\x30\n\x06status\x12\x11.autoLights.Light\x1a\x11.autoLights.Light\"\x00\x42\x1c\n\x03sdsB\rkademliaProtoP\x01\xa2\x02\x03kadb\x06proto3')



_VOTO = DESCRIPTOR.message_types_by_name['voto']
_LIGHT = DESCRIPTOR.message_types_by_name['Light']
voto = _reflection.GeneratedProtocolMessageType('voto', (_message.Message,), {
  'DESCRIPTOR' : _VOTO,
  '__module__' : 'automaticlights_pb2'
  # @@protoc_insertion_point(class_scope:autoLights.voto)
  })
_sym_db.RegisterMessage(voto)

Light = _reflection.GeneratedProtocolMessageType('Light', (_message.Message,), {
  'DESCRIPTOR' : _LIGHT,
  '__module__' : 'automaticlights_pb2'
  # @@protoc_insertion_point(class_scope:autoLights.Light)
  })
_sym_db.RegisterMessage(Light)

_AUTOMATICLIGHTS = DESCRIPTOR.services_by_name['AutomaticLights']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\003sdsB\rkademliaProtoP\001\242\002\003kad'
  _VOTO._serialized_start=37
  _VOTO._serialized_end=58
  _LIGHT._serialized_start=60
  _LIGHT._serialized_end=101
  _AUTOMATICLIGHTS._serialized_start=104
  _AUTOMATICLIGHTS._serialized_end=270
# @@protoc_insertion_point(module_scope)
